import type { Stack } from './init-detect.js'

type StarterRule = {
  readonly id: string
  readonly rule: string
}

type StackProfile = {
  readonly paths: readonly string[]
  readonly ignore: readonly string[]
  readonly rules: readonly StarterRule[]
}

const sharedRules: readonly StarterRule[] = [
  {
    id: 'one-responsibility',
    rule: 'one file means one responsibility — flag a file that gains a second responsibility instead of being split'
  },
  {
    id: 'no-duplication',
    rule: 'do not reimplement an existing helper or module — search before concluding something is new'
  },
  {
    id: 'behavioral-tests',
    rule: 'tests must assert observable behavior, not implementation internals'
  }
]

const sharedIgnore: readonly string[] = ['package-lock.json', '**/*.md']

const profiles: Record<Stack, StackProfile> = {
  node: {
    paths: ['src/**/*.ts', 'src/**/*.js'],
    ignore: sharedIgnore,
    rules: [
      ...sharedRules,
      {
        id: 'errors-at-boundaries',
        rule: 'errors are handled or deliberately propagated at module boundaries — flag silently swallowed errors'
      }
    ]
  },
  react: {
    paths: ['src/**/*.{ts,tsx}'],
    ignore: sharedIgnore,
    rules: [
      ...sharedRules,
      {
        id: 'state-colocation',
        rule: 'state lives in the closest component that needs it — flag state lifted without a consumer that requires it'
      },
      {
        id: 'effect-discipline',
        rule: 'useEffect only synchronizes with external systems — flag effects that derive state or handle user events'
      }
    ]
  },
  next: {
    paths: ['app/**/*.{ts,tsx}', 'src/**/*.{ts,tsx}', 'pages/**/*.{ts,tsx}'],
    ignore: sharedIgnore,
    rules: [
      ...sharedRules,
      {
        id: 'server-client-boundary',
        rule: 'data fetching belongs in server components — flag client components that fetch what a server parent could pass down'
      },
      {
        id: 'effect-discipline',
        rule: 'useEffect only synchronizes with external systems — flag effects that derive state or handle user events'
      }
    ]
  },
  electron: {
    paths: ['src/**/*.{ts,tsx}', 'electron/**/*.ts', 'main/**/*.ts'],
    ignore: sharedIgnore,
    rules: [
      ...sharedRules,
      {
        id: 'process-separation',
        rule: 'main and renderer responsibilities stay separated — flag renderer code reaching for node or main-process APIs directly'
      },
      {
        id: 'ipc-validation',
        rule: 'every IPC payload is validated in the main process before use — flag handlers that trust renderer input'
      }
    ]
  }
}

const starterSystemPrompt = [
  'You are a senior reviewer judging a staged diff. Deterministic style',
  'and formatting are enforced by linters that run before you — never',
  're-litigate them. Focus only on the judgment rules below. Use your',
  'read-only tools sparingly: read a file at most once, and never read',
  'documentation — judge only the code.'
]

const agentSnippet =
  'If a commit is blocked by the reviewer, read `.veto/runs/latest.json` and fix the findings, then commit again.'

const yamlList = (items: readonly string[]): string =>
  items.map((item) => `  - "${item}"`).join('\n')

const yamlRules = (rules: readonly StarterRule[]): string =>
  rules
    .map((entry) => `  - id: ${entry.id}\n    rule: ${entry.rule}`)
    .join('\n')

const yamlBlock = (lines: readonly string[]): string =>
  lines.map((line) => `  ${line}`).join('\n')

const renderStarterConfig = (stack: Stack): string => {
  const profile = profiles[stack]
  return [
    '# Starter reviewer config generated by `veto init`.',
    `# The rules below are placeholder examples shaped for a ${stack} project —`,
    "# replace them with your team's real judgment calls.",
    'name: architect',
    'mode: static',
    'model: claude-sonnet-4-6',
    'effort: low',
    'maxTurns: 8',
    'paths:',
    yamlList(profile.paths),
    'ignore:',
    yamlList(profile.ignore),
    'systemPrompt: |',
    yamlBlock(starterSystemPrompt),
    'rules:',
    yamlRules(profile.rules),
    ''
  ].join('\n')
}

export { agentSnippet, renderStarterConfig }
